apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: dax-trading
type: Opaque
data:
  # Base64 encoded values - replace with actual encoded secrets
  POSTGRES_USER: ZmlucmxfdXNlcg==  # finrl_user
  POSTGRES_PASSWORD: UkVQTEFDRV9XSVRIX1lPVVJfUEFTU1dPUkQ=  # REPLACE_WITH_YOUR_PASSWORD (base64 encoded)
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: dax-trading
data:
  POSTGRES_DB: "dax_trading"
  POSTGRES_USER: "finrl_user"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: dax-trading
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: dax-trading
  labels:
    app: postgres
spec:
  serviceName: postgres-service
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - $(POSTGRES_USER)
            - -d
            - $(POSTGRES_DB)
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - $(POSTGRES_USER)
            - -d
            - $(POSTGRES_DB)
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2"
      volumes:
      - name: init-sql
        configMap:
          name: postgres-init-sql
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-path
      resources:
        requests:
          storage: 100Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-sql
  namespace: dax-trading
data:
  schema.sql: |
    -- This will be populated from services/postgres/init-sql/schema.sql
    -- See the full schema in the services/postgres/init-sql/ directory