apiVersion: apps/v1
kind: Deployment
metadata:
  name: dax-llm-service
  namespace: dax-trading
  labels:
    app: dax-llm-service
    tier: ai-inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dax-llm-service
  template:
    metadata:
      labels:
        app: dax-llm-service
        tier: ai-inference
    spec:
      containers:
      - name: dax-llm-inference
        image: ghcr.io/dan8992/dax-llm-service:latest
        ports:
        - containerPort: 8000
          name: api-port
        env:
        - name: MODEL_NAME
          value: nlptown/bert-base-multilingual-uncased-sentiment
        - name: TRANSFORMERS_CACHE
          value: /tmp/transformers_cache
        - name: GPU_MEMORY_UTILIZATION
          value: "0.9"
        - name: MAX_MODEL_LEN
          value: "4096"
        - name: TENSOR_PARALLEL_SIZE
          value: "2"
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: "2"
            memory: 4Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: dax-llm-service-service
  namespace: dax-trading
  labels:
    app: dax-llm-service
spec:
  selector:
    app: dax-llm-service
  ports:
  - name: api
    port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP