apiVersion: apps/v1
kind: Deployment
metadata:
  name: finbert-trading-llm
  namespace: dax-trading
  labels:
    app: finbert-trading-llm
    tier: ai-inference
    version: institutional
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finbert-trading-llm
  template:
    metadata:
      labels:
        app: finbert-trading-llm
        tier: ai-inference
    spec:
      containers:
      - name: finbert-api
        image: ghcr.io/dan8992/finbert-trading-llm:latest
        ports:
        - containerPort: 8001
          name: api-port
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: FLASK_ENV
          value: production
        - name: MODEL_CACHE_DIR
          value: /tmp/model_cache
        - name: POSTGRES_HOST
          value: "postgres-service"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "finrl_dax"
        - name: POSTGRES_USER
          value: "finrl_user"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        resources:
          requests:
            cpu: 1000m
            memory: 2Gi
          limits:
            cpu: "4"
            memory: 8Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: finbert-trading-llm-service
  namespace: dax-trading
  labels:
    app: finbert-trading-llm
spec:
  selector:
    app: finbert-trading-llm
  ports:
  - name: api
    port: 8001
    targetPort: 8001
    protocol: TCP
  type: ClusterIP